Homework5
niskhakov/Admins pull request #2
Opened 2018-07-24 22:56 UTC by niskhakov

2018-07-25 19:15 UTC, Frodox reviewed
Вместе с напарником делали? :) ДЗ то самостоятельное)

2018-07-25 19:15 UTC, Frodox commented on personal/homework/lesson5/readme.md
> +Актуальная версия находится по адресу: [+Dropbox Paper: Admins: HW → WEB](https://paper.dropbox.com/doc/Admins-HW-WEB-Avoss3tD1CtyfWYir1v7S)
Актуальную версию положи в git, сюда. Пользоваться Dropbox не нужно.

2018-07-25 19:15 UTC, Frodox commented on personal/homework/lesson5/readme.md
> +Актуальная версия находится по адресу: [+Dropbox Paper: Admins: HW → WEB](https://paper.dropbox.com/doc/Admins-HW-WEB-Avoss3tD1CtyfWYir1v7S)
И что читать то тогда?

2018-07-25 19:15 UTC, Frodox commented on personal/homework/lesson5/readme.md
> +Также ссылка на репозиторий: [+GitHub: Admins: HW → WEB](https://github.com/niskhakov/Admins/tree/Homework5/personal/homework/lesson5)
Это избыточно, это же в самой репе лежит

2018-07-28 19:58 UTC, Frodox requested changes

2018-07-28 19:58 UTC, Frodox commented on personal/homework/lesson5/readme.md
> +2. Добавили исполнение файлу prepare.sh и выполнили его
можно саму команду)

2018-07-28 19:58 UTC, Frodox commented on personal/homework/lesson5/readme.md
> +  Немного не понял как оформить отчет по первому заданию (Строку запуска uwsgi приложения????). Пусть будет так:
после кавычек - перенос строки, далее можно экранирова переносы строк, чтобы было читаемо. аля
```
some command \
  arg1 \
  args2
```

2018-07-28 19:58 UTC, Frodox commented on personal/homework/lesson5/readme.md
> +- **cp -R -** рекурсивное перемещение
**перемещение** ли?

2018-07-28 19:58 UTC, Frodox commented on personal/homework/lesson5/readme.md
> +- **supervisotctl start** - запускает процесс
опечаточка

2018-08-01 13:57 UTC, niskhakov commented on personal/homework/lesson5/readme.md
> +Актуальная версия находится по адресу: [+Dropbox Paper: Admins: HW → WEB](https://paper.dropbox.com/doc/Admins-HW-WEB-Avoss3tD1CtyfWYir1v7S)
Исправил, удалил эти строчки

2018-08-01 13:58 UTC, niskhakov commented on personal/homework/lesson5/readme.md
> +Также ссылка на репозиторий: [+GitHub: Admins: HW → WEB](https://github.com/niskhakov/Admins/tree/Homework5/personal/homework/lesson5)
ДЗ делал самостоятельно, просто на компьютере в git config-е была прописана другая почта (на нее привязан другой аккаунт github - заброшенный)

2018-08-01 13:59 UTC, niskhakov commented on personal/homework/lesson5/readme.md
> +2. Добавили исполнение файлу prepare.sh и выполнили его
Обновил файл: (приведу сюда изменение, еще не знаю как это правильно делать)
    ```
    chmod +x prepare.sh
    ./prepare.sh
    ```

2018-08-01 14:04 UTC, niskhakov commented on personal/homework/lesson5/readme.md
> +  Немного не понял как оформить отчет по первому заданию (Строку запуска uwsgi приложения????). Пусть будет так:
Сделал:
    ```
    uwsgi \
        --plugins=python \
        --http-socket=0.0.0.0:80 
        --wsgi-file /opt/webcode/former/process/webrunner.py \
        --static-map /form=/opt/webcode/former/form/index.html \
        --processes=5 \
        --master \
        --pidfile=/tmp/formdig.pid \
        --vacuum \
        --max-requests=5000
    ```

2018-08-01 14:04 UTC, niskhakov commented on personal/homework/lesson5/readme.md
> +- **cp -R -** рекурсивное перемещение
Копирование, перепутал с mv

2018-08-01 14:05 UTC, niskhakov commented on personal/homework/lesson5/readme.md
> +- **supervisotctl start** - запускает процесс
Исправил, сделал пару коммитов, которые исправляют вышеуказанные недочеты

2018-08-03 11:16 UTC, Frodox commented on personal/homework/lesson5/readme.md
> +    ```uwsgi \
после трёх кавычек - перенос строки, с новой строки - код. а на этой строки - какой код (как подсвечивать. python/bash)

2018-08-03 11:17 UTC, Frodox approved these changes

2018-08-06 03:45 UTC, merged